### PR TITLE
Expand the MANIFEST.in to include all needed files for packaging.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Added all resource csv files to the manifest so that they are included in the distribution.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Build source library and verified that all dependent files are in the resulting distribution.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-2927) $ flake8 dqc_us_rules/
(dqc)  chrislococo [dqc] (XS-2927) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-2927) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-2927) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-2927) $ nosetests tests
..................................................................
----------------------------------------------------------------------
Ran 66 tests in 0.042s

OK
```

#### Result: QA +10

**Comment by andrewperkins-wf** [comment]
+1 Merging - reviewed and QAed

**Pull request merged**
