### PR TITLE
Add configs for DQC 14

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Updated configs.
- No tests since it's a config change.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by sagesmith-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Used the document Jay attached and verified the "CostOfServices" and "PriceRiskDerivativeLiabilitiesAtFairValue" concepts fired DQC14.  

QA +1

**Comment by andrewperkins-wf** [comment]
Reviews and QA done.  Merging.

**Pull request merged**
