### PR TITLE
Break out DATE_BOUNDS_DICT into a csv

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes:

- Fix Flake8 errors
- Broke DATE_BOUNDS_DICT out into a csv

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+10 QA performed with the arelle UI

**Comment by andrewperkins-wf** [comment]
Reviews were done, testing was completed.

+1 on code, looks good.  Merging.

**Pull request merged**
