### PR TITLE
Updated __init__.py to reflect version status and updated _pkg_meta.p…

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Changed init to reflect new version.
- Changed pkg_meta to reflect new release candidate number.

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

##### Once checklist is complete, @hefischer  @andrewperkins-wf please review for merge.

…y to increment RC number.

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
+1 - not sure if you need to update any of the other rules' versions as well (if you touched any that hadn't been updated yet)?

**Comment by allenbross-wf** [comment]
All of the rules are correct to the best of my knowledge for this version.

**Comment by andrewperkins-wf** [comment]
+1 to last change, pending Travis

**Comment by joyreistad-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
QA +10, nothing to test as this is a version change. Merging.

**Pull request merged**
