### PR TITLE
XS-5227 Changing package version numbers

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Changed package version number

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by joyreistad-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
QA +10: Loaded branch into Arelle and verified that version of DQC was 5.0

**Comment by allenbross-wf** [comment]
Code reviewed and QAed.  Merging.

**Pull request merged**
