### PR TITLE
XS-3312 Removed problematic space and incremented release

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Removed space that was disallowing a member match
- Incremented release tag as the change is a bug fix and will necessitate a new release.

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
QA +10 Verified

**Comment by andrewperkins-wf** [comment]
Reviewed and verified, merging

**Pull request merged**
