### PR TITLE
XS-5260

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Added code check to DQC 0046
- Added code check to DQC 0008
- Fixed an issue with DQC 0008 unnecessarily creating resource files.
- Incremented version number

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1, nice usages of early breaks

**Comment by joyreistad-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by joyreistad-wf** [comment]
Verified:

Manual testing: ran the attached filing through Arelle using this version of DQC as a plugin and no longer saw the DQC.US.0008 error that was worked on in this ticket

Flake8 on dqc_us_rules:
```
(dqc)  joyreistad [dqc] ((HEAD detached at allen/XS-5260)) $ flake8 dqc_us_rules/
(dqc)  joyreistad [dqc] ((HEAD detached at allen/XS-5260)) $
```
Flake8 on tests:
```
(dqc)  joyreistad [dqc] ((HEAD detached at allen/XS-5260)) $ flake8 tests
(dqc)  joyreistad [dqc] ((HEAD detached at allen/XS-5260)) $
```
Nosetest result:
```
(dqc)  joyreistad [dqc] ((HEAD detached at allen/XS-5260)) $ nosetests tests
..............................................................................................................
----------------------------------------------------------------------
Ran 110 tests in 0.124s

OK
```
Result: QA +10

**Comment by allenbross-wf** [comment]
Code reviewed and QAed.  Merging.

**Pull request merged**
