### PR TITLE
Update pin to 2.0.0RC13

### PR DESCRIPTION
**Pull request by chrislococo-wf**
### Changes:

- Updated pin to 2.0.0RC13

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
+10 - simple version change

Merging.

**Comment by andrewperkins-wf** [comment]
Will merge, pending Travis

**Pull request merged**
