### PR TITLE
XS-5059 Added missing members to ReinsurancePremiumsForInsuranceCompaniesByProductSegmentAxis

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Added missing members
- Incremented version number

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
#### QA Steps:

- Manual testing: <Enter Manual testing notes here.>
- Flake8 on dqc_us_rules:
```
<Paste output of flake8 on the dqc_us_rules directory here.>
```
- Flake8 on tests:
```
<Paste output of flake8 on the tests directory here.>
```
- Nosetest result:
```
<Paste output of nose tests here.>
```

#### Result: <Put result here.>

**Comment by mindeerickson-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
Previous QA applies.  Doc only change added.  QA + 10

**Pull request merged**
