### PR TITLE
XS-3273 Pulling in changes from master

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Pulling in changes from master specifically for rule DQC 5 and DQC 15.

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by allenbross-wf** [comment]
When this is merged, please also merge the documentation changes in https://github.com/DataQualityCommittee/dqc_us_rules/pull/214

**Comment by andrewperkins-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by joyreistad-wf** [comment]
Verified
* Ran arelle locally on pst-20161001_3_xbrl_filing_documents.zip. when validated only the expected DQC rule was fired (DQC.US.0036.1)

QA +10

**Comment by andrewperkins-wf** [comment]
All process followed - reviewed and tested. Merging.

**Pull request merged**
