### PR TITLE
XS-5188

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Added 600+ elements to negative number list.  Removed 2.
- Incremented version number

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by joyreistad-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
QA +10: Ran the attached doc and it validated correctly with 6 DQC 15 errors as pointed out by Allen.

**Comment by allenbross-wf** [comment]
Code reviewed and QAd. Merging.

**Pull request merged**
