### PR TITLE
XS-3030: Flake8 cleanup for 0014

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Corrected flake8 issues with 0014
- Corrected flake8 issues with 0014's test file.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
QA Testing

# Manual Testing
* Tested rules 14 and 18 and both fired

# Flake8 Tests
```
venv_3_4) LS2-00222:dqc_us_rules andrewperkins$ flake8 dqc_us_rules
(venv_3_4) LS2-00222:dqc_us_rules andrewperkins$ flake8 tests
```

# Unit Tests
```
.................................................................................
----------------------------------------------------------------------
Ran 81 tests in 0.052s
```

**Pull request merged**
