### PR TITLE
Update version to 2.0.0RC14

### PR DESCRIPTION
**Pull request by chrislococo-wf**
### Changes:

- Updated the pin to release 2.0.0RC14

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by davidtauriello** [comment]
@andrewperkins-wf - please remember to "...merge it (https://github.com/DataQualityCommittee/dqc_us_rules/pull/178) to master and merge master over to the next_q1 branch once we have finished code reviewing and testing the changes" so this RC is complete with DQC-approved rules.

**Comment by chrislococo-wf** [comment]
@davidtauriello do you want #178 included in before we release 2.0.0RC14?

**Comment by davidtauriello** [comment]
@chrislococo-wf – I *think* that’s what Andrew was planning for #178
<https://github.com/DataQualityCommittee/dqc_us_rules/pull/178> in his
comment to me earlier this week. The goal is to get master and next_q1_16
branches consistent in terms of v1.1.1 approved rules.



Thanks and let me know if there’s anything I can do to help.



*From:* Chris Lo Coco [mailto:notifications@github.com]
*Sent:* Friday, July 15, 2016 2:38 PM
*To:* DataQualityCommittee/dqc_us_rules
*Cc:* David Tauriello; Mention
*Subject:* Re: [DataQualityCommittee/dqc_us_rules] Update version to
2.0.0RC14 (#180)



@davidtauriello <https://github.com/davidtauriello> do you want #178
<https://github.com/DataQualityCommittee/dqc_us_rules/pull/178> included in
before we release 2.0.0RC14?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DataQualityCommittee/dqc_us_rules/pull/180#issuecomment-233033385>,
or mute the thread

**Comment by andrewperkins-wf** [comment]
reviewed, tested, merging

**Pull request merged**
