### PR TITLE
New configs for DQC13

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Updated configs
- Config change, so no tests needed.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
QA +1

**Comment by andrewperkins-wf** [comment]
Reviews and QA done, merging.

**Pull request merged**
