### PR TITLE
XS-3078: Exclude S-1 and S-11 reports from DQC_0005

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Added an exception list and validation skipping to 0005.
- Added a new unit test to test the skipping mechanic.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1 to fix

**Comment by andrewperkins-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Verified using the attached project ("XS-3078 NewProject.zip"). Additionally, I have attached the filing documents used to test ("min-20160531_6_xbrl_filing_documents.zip" has DocumentType of "S-1" and "min-20160531_7_xbrl_filing_documents.zip" has DocumentType of "10-Q").

The 10-Q version will fire three DQC 5 errors (DQC0005.17, DQC0005.48, and DQC0005.49).

**Comment by andrewperkins-wf** [comment]
reviews and verification completed - merging.

**Pull request merged**
