### PR TITLE
XS-4195

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Initial implementation of DQC.US.0008
- Changed package version number

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by joyreistad-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
QA + 10 - tested locally and verified the new validation fires as expected.

**Pull request merged**
