### PR TITLE
XS-3091 DQC Rule 1 Needs All Facts

### PR DESCRIPTION
**Pull request by mindeerickson-wf**
##### Pull request for: [XS-3091](https://jira.webfilings.com/browse/XS-3091)
[XS-3091](https://jira.webfilings.com/browse/XS-3091) - DQC Rule 1 Needs All Facts

-
#### Changes:
- Changes to dqc_us_0001.py and /utils.facts.py to fix rule 1 so that all facts are used instead of a single fact
- Changes to test_dqc_us_0001.py to fix the unit tests that broke due to the abovementioned changes
- Changes to test_dqc_us_0005.py to fix a broken unit test.  This test was broke from the work in XS-3078 but was not caught in dev or QA during the work and testing for that ticket.

#### Testing:
- I have attached the doc to use for testing.  The doc was the doc used to test this rule when it was first implemented (XS-3026) and should fire DQC 1 five times.  Additionally, follow the testing suggestion noted in the description of the ticket.  

-
Please review: @jasonleinbach-wf @chrislococo-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Manually tested with document attached to the ticket, multiple instances of the same error are thrown when the error is repeated.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-3091) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-3091) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-3091) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-3091) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-3091) $ nosetests tests/
...................................................................................................
----------------------------------------------------------------------
Ran 99 tests in 0.082s

OK
```

#### Result: QA +10

**Comment by andrewperkins-wf** [comment]
reviewed, QA'ed, merging.

**Comment by andrewperkins-wf** [comment]
Not merging - this needs to be pointed at the q1_next branch.

**Pull request closed without merging**
