### PR TITLE
Add args and kwargs.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Add args and kwargs to every validation for future proofing.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
Note: a broken unit test slipped in.  Minde is fixing it currently as part of XS-3091.

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Tested various documents to make sure they are all firing still as normal. 
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-2947) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-2947) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-2947) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-2947) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-2947) $ nosetests
.................................................................E.................................
======================================================================
ERROR: Tests to make sure excluded reports are not validated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chrislococo/.pythonz/pythons/CPython-3.4.3/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(*args, **keywargs)
  File "/Users/chrislococo/code/wf/dqc/tests/unit_tests/test_dqc_us_0005.py", line 262, in test_report_exclusion
    dqc_us_0005.validate_facts(self.mock_model)
  File "/Users/chrislococo/code/wf/dqc/dqc_us_rules/dqc_us_0005.py", line 84, in validate_facts
    dei_list = facts.get_facts_dei(['DocumentType'], model_xbrl=val.modelXbrl)
  File "/Users/chrislococo/code/wf/dqc/dqc_us_rules/util/facts.py", line 273, in get_facts_dei
    list_dei.extend(lookup_dei_facts(dei, model_xbrl, False))
  File "/Users/chrislococo/code/wf/dqc/dqc_us_rules/util/facts.py", line 292, in lookup_dei_facts
    f for f in model_xbrl.facts
TypeError: 'Mock' object is not iterable

----------------------------------------------------------------------
Ran 99 tests in 0.463s

FAILED (errors=1)
```

#### Result: QA +10, unit test failure is handled in a follow up already in flight.

**Comment by chrislococo-wf** [comment]
+1 Merge

**Comment by chrislococo-wf** [comment]
QA +10:
Nosetests corrected with master merge:
```(dqc)  chrislococo [dqc] (XS-2947) $ nosetests tests/
...................................................................................................
----------------------------------------------------------------------
Ran 99 tests in 0.086s

OK
```

**Pull request merged**
