### PR TITLE
Locator consistency for DQC 5

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Added a sort to the traversal in DQC5 to ensure consistency in locators.
- Based off of https://github.com/DataQualityCommittee/dqc_us_rules/pull/117

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1 but I think we can, and maybe should have the locators sorted on the SW side too

**Comment by jasonleinbach-wf** [comment]
That's a good idea.  That being said, I think it'd still be a problem with hashing (even though this validation isn't VAC-able.)

**Comment by sagesmith-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Testing notes can be found in the Jira ticket.  

QA +1

**Comment by andrewperkins-wf** [comment]
reviews and QA finished.  Merging.

**Pull request merged**
