### PR TITLE
Updated version to 2.0.0 RC 15

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Updated pin to RC15

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: None required as it is a version update
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (update_pin) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (update_pin) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (update_pin) $ flake8 tests/
(dqc)  chrislococo [dqc] (update_pin) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (update_pin) $ nosetests tests/
...........................................................................................................
----------------------------------------------------------------------
Ran 107 tests in 0.097s

OK
```

#### Result: QA +10

**Comment by andrewperkins-wf** [comment]
Tested and reviewed, PRed to correct branch - merging.

**Pull request merged**
