### PR TITLE
XS-3098 Flake8 Errors in test from XS-3076

### PR DESCRIPTION
**Pull request by mindeerickson-wf**
##### Pull request for: [XS-3098](https://jira.webfilings.com/browse/XS-3098)
[XS-3098](https://jira.webfilings.com/browse/XS-3098) - Flake8 Errors in test/ from XS-3076

-
#### Changes:
- Fixed flake8 issues that occurred due to the work in XS-3076

#### Testing:
- NOTE:  One unit test for DQC5 will not pass.  This was fixed in XS-3091 (which hasn't been merged) so I did not fix this in this ticket.  

-
Please review: @jasonleinbach-wf @chrislococo-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf

### CODE REVIEW

**Comment by sagesmith-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Manual testing unneeded as changes were in unit tests.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-3098) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-3098) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-3098) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-3098) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-3098) $ nosetests tests/
.................................................................E...................................
======================================================================
ERROR: Tests to make sure excluded reports are not validated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chrislococo/.pythonz/pythons/CPython-3.4.3/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(*args, **keywargs)
  File "/Users/chrislococo/code/wf/dqc/tests/unit_tests/test_dqc_us_0005.py", line 262, in test_report_exclusion
    dqc_us_0005.validate_facts(self.mock_model)
  File "/Users/chrislococo/code/wf/dqc/dqc_us_rules/dqc_us_0005.py", line 84, in validate_facts
    dei_list = facts.get_facts_dei(['DocumentType'], model_xbrl=val.modelXbrl)
  File "/Users/chrislococo/code/wf/dqc/dqc_us_rules/util/facts.py", line 273, in get_facts_dei
    list_dei.extend(lookup_dei_facts(dei, model_xbrl, False))
  File "/Users/chrislococo/code/wf/dqc/dqc_us_rules/util/facts.py", line 292, in lookup_dei_facts
    f for f in model_xbrl.facts
TypeError: 'Mock' object is not iterable

----------------------------------------------------------------------
Ran 101 tests in 0.087s

FAILED (errors=1)
```

#### Result: QA +10, unit test failure is already handled in an in flight ticket.

**Comment by andrewperkins-wf** [comment]
reviewed and tested - merging.

**Comment by chrislococo-wf** [comment]
+1 merge

**Comment by chrislococo-wf** [comment]
#### +10 QA:

Nosetest error cleaned up by upstream merge:

```
(dqc)  chrislococo [dqc] (XS-3076) $ nosetests tests/
.....................................................................................................
----------------------------------------------------------------------
Ran 101 tests in 0.086s

OK
```

**Pull request merged**
