### PR TITLE
XS-3123: Corrections to the 33/36 interactions.

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Used for/else logic to handle dimensionless 36-33 interactions.
- Updated unit tests to reflect changes.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
Additional followup work for expansion of the test cases around this has been ticketed for future work.

**Comment by mindeerickson-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Testing notes can be found in the Jira ticket. 

QA +1

**Comment by jasonleinbach-wf** [comment]
Reviewed and verified.  Merging.

**Pull request merged**
