### PR TITLE
Updates to DQC 13 for proper condition checks

### PR DESCRIPTION
**Pull request by andrewperkins-wf**
### Changes:

DQC 13 was not handling a situation where the exists condition didn't exist but the addends did.  Fixed it to handle that situation.

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Testing:
* Tested with the three attached documents and all passed:
** min-20160630_5_xbrl_filing_documents.zip - fires DQC 13 four times
** pst-20150925_120_xbrl_filing_documents.zip - fires DQC 13 one time
** testco-20141231_3462.xml (NOTE: this is the filing doc found here in DQC_0013.2777.3462) - does not fire DQC 13

QA +1

**Comment by andrewperkins-wf** [comment]
Closing, this is being included in [PR 166] to fix the Travis CI errors.

**Pull request closed without merging**
