### PR TITLE
Xs 3056

### PR DESCRIPTION
**Pull request by joyreistad-wf**
### Changes:

- Changed default_dped_fact to eop_fact in dqc_us_0022_0036 so that the exception dqcErrorLog:unresolvedParametes is no longer raised

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1 - looks like DQC/master was inadvertently merged into this, but it's just documentation changes, so it's okay to bring them along to next_q1_16.

**Comment by chrislococo-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Testing notes can be found in the Jira ticket.  

QA +1

**Comment by jasonleinbach-wf** [comment]
Reviewed and verified.  Merging.

**Pull request merged**
