### PR TITLE
Add errorCount to DQC1

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Add errorCount to errors with locators.
- Update tests.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Ran a few DQC 1 documents through.  We found some issues and have created a ticket to address that (XS-3137).  This error count ticket is ok to move forward, however.

QA +1

**Comment by jasonleinbach-wf** [comment]
Reviewed and verified.  Merging.

**Pull request merged**
