### PR TITLE
Fix typo in DQC 18.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Fixed typo.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
+1

**Comment by Lanakire** [comment]
+1

**Comment by Lanakire** [comment]
Commenting on my personal account, since I am out of the office.

**Comment by sagersmith8** [comment]
+1

**Comment by mindeerickson-wf** [comment]
QA +1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
Version bump reviewed.  Changes reviewed and verified.  Merging.

**Pull request merged**
