### PR TITLE
XS-5226

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Merged in next_q1_17
- fixed a bug in DQC.US.0001
- Set the proper version numbers

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by joyreistad-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
QA +10: Validated the provided file against the branch and it yielded 1 DQC.US.0001.66 and 3 PrimaryItemDimensionallyInvalidErrors as described above.

**Comment by allenbross-wf** [comment]
Code Reviewed, and QAed.  Merging.

**Pull request merged**
