### PR TITLE
XS-3311  The space at the end of CorporateNonSegmentMember was not al…

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Removed a space so the member will match.

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
Good find.  +1

**Comment by mindeerickson-wf** [comment]
Testing notes can be found in the Jira ticket.

+10

**Comment by andrewperkins-wf** [comment]
reviewed and tested.  Merging.

**Comment by davidtauriello** [comment]
@allenbross-wf & @andrewperkins-wf  - I think this fix also needs to be applied to the file in master branch, as that's where I introduced the error that was then pulled into next_q1_16 branch.  If that's correct, a new v1 release also needs to be published.

**Pull request merged**
