### PR TITLE
DQC 18 styling.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Styleguide changes as suggested in https://github.com/DataQualityCommittee/dqc_us_rules/pull/84
- Based off of https://github.com/DataQualityCommittee/dqc_us_rules/pull/93

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1 for merge

**Comment by chrislococo-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1 refresh

**Comment by andrewperkins-wf** [comment]
QA +10

QA Testing:

# Manual Testing
* Ran a document that fired DQC 18 and saw it fire
* Ran a document that fired DQC 5 and saw it fire

# Unit Tests
```
.............................................................................
----------------------------------------------------------------------
Ran 77 tests in 0.047s
```

# flake8
Ran clean
```
(venv_3_4) LS2-00222:dqc_us_rules andrewperkins$ flake8 dqc_us_rules
(venv_3_4) LS2-00222:dqc_us_rules andrewperkins$ flake8 tests
```

**Pull request merged**
