### PR TITLE
Fix formatting of bad if statement

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes:

- Moved _min_dec_valid call inside of _values_unequal call

Reasoning: _min_dec_valid was created to prevent the _values_unequal call from throwing an error so it is logical to check if min_dec is valid inside _values_unequal instead of in every if where _value_unequal is called 

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by sagesmith-wf** [comment]
Convenience PR https://github.com/sagesmith-wf/dqc_us_rules/pull/2

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+2

**Comment by chrislococo-wf** [comment]
QA:
- Manual testing on throwing 0004 errors works correctly.
- Unit tests: ```(dqc)  chrislococo [dqc] (xs-2906) $ nosetests tests
.................................................................
----------------------------------------------------------------------
Ran 65 tests in 0.035s

OK```
- ```(dqc)  chrislococo [dqc] (xs-2906) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (xs-2906) $```
- ```(dqc)  chrislococo [dqc] (xs-2906) $ flake8 tests/
tests/unit_tests/test_dqc_us_0033_0036.py:137:55: E261 at least two spaces before inline comment
tests/unit_tests/test_dqc_us_0033_0036.py:171:55: E261 at least two spaces before inline comment
tests/unit_tests/test_dqc_us_0033_0036.py:202:55: E261 at least two spaces before inline comment
(dqc)  chrislococo [dqc] (xs-2906) $```

Putting on hold waiting for the flake8 changes in https://github.com/DataQualityCommittee/dqc_us_rules/pull/66 before merging.

**Comment by chrislococo-wf** [comment]
+1 Master merge

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Manual testing of 0004 still fires.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (xs-2906) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (xs-2906) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (xs-2906) $ flake8 tests/
(dqc)  chrislococo [dqc] (xs-2906) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (xs-2906) $ nosetests tests/
..................................................................
----------------------------------------------------------------------
Ran 66 tests in 0.080s

OK
(dqc)  chrislococo [dqc] (xs-2906) $
```

#### Result: QA +1

**Comment by andrewperkins-wf** [comment]
+1 - merging

**Pull request merged**
