### PR TITLE
Add new configs for DQC1.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Added new configs from spreadsheet here: https://github.com/DataQualityCommittee/dqc_us_rules/pull/110

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Manually tested existent filing docs that throw 0001 errors.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-3058) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-3058) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-3058) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-3058) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-3058) $ nosetests tests/
..................................................................................................
----------------------------------------------------------------------
Ran 98 tests in 0.082s

OK
```

#### Result: Pending for more test cases.

**Comment by andrewperkins-wf** [comment]
code reviewed and tested.  Merging.

**Pull request merged**
