### PR TITLE
XS-4545 Removing elements from DQC.US.0015 test.

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes: 

- Removed 12 elements from resource file
- Incremented version number

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1 merge conflict resolution, pending travis.

**Comment by jasonleinbach-wf** [comment]
QA + 10

**Pull request merged**
