### PR TITLE
XS-3611 DQC merging unit test fix from master into next_q3_16

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Merging in master to get a unit test fix

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by sagesmith-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+10 build passes unit tests cleanly.

**Comment by andrewperkins-wf** [comment]
All process followed - merging.

**Pull request merged**
