### PR TITLE
XS-3018 Handle SG followup from XS-2905

### PR DESCRIPTION
**Pull request by mindeerickson-wf**
##### Pull request for: [XS-3018](https://jira.webfilings.com/browse/XS-3018)
[XS-3018](https://jira.webfilings.com/browse/XS-3018) - Handle SG followup from XS-2905

-
#### Changes:
Fixed style guide issues that were discovered while testing XS-2905

-
Please review: @jasonleinbach-wf @chrislococo-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
Tested with XS-3078 doc.

```
----------------------------------------------------------------------
Ran 101 tests in 1.038s

OK
```

+10.

**Comment by jasonleinbach-wf** [comment]
Reviewed and verified.  Merging.

**Pull request merged**
