### PR TITLE
Update rule 1 message

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes:

- Fixed messages
- Updated logic
- Updated unit tests

#### Pull request process
- [x] Full description of changes provided above.
- [x] Reviewed by another person (+1) 
- [x] If a code change, reviewed by a second person. (+1) 
- [ ] QA'd to the specifications listed [here](../README.md#poop). Documentation only changes do not require the formal code quality assurance process. (+10) 

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Testing notes can be found in the Jira ticket.

QA +1

**Comment by andrewperkins-wf** [comment]
All reviews and testing completed - merging.

**Pull request merged**
