### PR TITLE
Update DQC1 configs.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
### Changes:

- Updated config

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
+1 pending smithy

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Tested in Arelle app with this branch and confirmed that neither concept is still firing a 0001 error.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-3252) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-3252) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-3252) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-3252) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-3252) $ nosetests tests/
..........................................................................................................
----------------------------------------------------------------------
Ran 106 tests in 0.096s

OK
```

#### Result: QA +10

**Pull request merged**
