### PR TITLE
Fixed error when filing didn't specify a decimal

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes

- Checked for a scale value of NaN because it was throwing an error
- Added a defensive check for a scale value of None
- Updated requirements_dev.txt because it was targeting the wrong version of lxml
- Fixed imports for unit tests for 0004 

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
Review completed in https://github.com/Workiva/dqc_us_rules/pull/6

**Comment by chrislococo-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
+1 - this was a specific error around missing decimal attributes.  Merging.

**Comment by jasonleinbach-wf** [comment]
+10 - verified with a doc with missing decimal attributes.

**Pull request merged**
