### PR TITLE
Update next_q1_16 with current DQC master.

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Update next_q1_16 branch with current master of DQC.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by sagesmith-wf** [comment]
👍 +1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
Nothing to test - this has all been tested as part of master.

**Comment by andrewperkins-wf** [comment]
+10 testing

**Pull request merged**
