### PR TITLE
XS-3290 DQC 13 occasionally throwing an error

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Added a filter to the precondition sum to remove nulls
- Added a unit test to handle scenario

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Testing notes can be found in the Jira ticket.

+10

**Comment by andrewperkins-wf** [comment]
Reviewed and tested.  PRed to correct branch.  Merging.

**Pull request merged**
