### PR TITLE
XS-3700 DQC 0005 Adding forms to exclusion list for 

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Added all currently possible S- form types including amendments.

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
@allenbross-wf Looks like Travis failed.

**Comment by allenbross-wf** [comment]
It's passing travis now.

**Comment by joyreistad-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+10 - integration tests pass.  Merging.

**Pull request merged**
