### PR TITLE
Updated DQC15 configs

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Updated inclusions
- Updated exclusions

No tests - config change.

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+1

**Comment by sagesmith-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
Verified using the attached project/filing doc. I chose to add four concepts that were added and DQC15 fired on all four. I made one fact with a concept that was removed and verified the rule did not fire on the concept. I made two facts that had axis/members that were added to the exclusions list and verified DQC15 did not fire on them. 

QA +1

**Comment by andrewperkins-wf** [comment]
Tested, reviewed, merging

**Pull request merged**
