### PR TITLE
XS-2873: Document the SDLC

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Recreation of the original Pull request found [here](https://github.com/DataQualityCommittee/dqc_us_rules/pull/156)

#### Pull request process
- [x] Full description of changes provided above.
- [x]  Reviewed by another person (+1)
- [x] If a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed. Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by sagesmith-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+10 - No functional change.

**Comment by jasonleinbach-wf** [comment]
Reviewed and verified.  Merging.

**Pull request merged**
