### PR TITLE
update v1 DQC_0005 and DQC_0015

### PR DESCRIPTION
**Pull request by davidtauriello**
changes for DQC approved revisions (Feb, Apr, May meetings)

### CODE REVIEW

**Comment by davidtauriello** [comment]
@andrewperkins-wf - thanks for a great conversation today about this update and the next phase of tasks related to this project (documentation, clean up). These are documentation updates for rules revised by DQC in 2016 which should be reviewed and merged as part of the v1 update release - please wait for instructions on the .xlsx file, as it's not yet complete. 

@susanyount-wf @campbellpryde @amibeers - I partially updated the memberexclusions.xlsx file from the V2 version in the next_q1_16 branch - **as far as I can tell, some of the members listed in appendix b of dqc_0015.md were not on the V2 file in the next_q1_branch (see highlighted rows in .xlsx in this pull** - let me know if you'll update the .xlsx or if the appendix b needs to be revised. 

All: I did not update the ListOfElements.xlsx file.

**Comment by davidtauriello** [comment]
spoke to @campbellpryde and updated DQC_0015 .md and .xlsx file.

**Comment by davidtauriello** [comment]
line items identified in appendix b of dqc_0015 rule submission form have been removed from the .xlsx

@andrewperkins - code changes for the memberexclusion @campbellpryde outlined in email earlier plus code changes to exclude Forms S-1 and S-11 from dqc_0005 and the documentation changes in this branch are what's needed to publish a 'latest release' for V1 as discussed earlier today.  Let me know if you have questions.

**Comment by davidtauriello** [comment]
@andrewperkins-wf - after the additional member exclusion @campbellpryde noted is added to this file:  https://github.com/DataQualityCommittee/dqc_us_rules/blob/next_q1_16/dqc_us_rules/resources/DQC_US_0015/dqc_15_exclusion_rules.csv the contents of this csv should be copied to the corresponding v1 file as part of 'latest release', as this file has not been modified since 12/15. Let me know if you have questions.

**Comment by andrewperkins-wf** [comment]
+1 on review.  No code changes, only documentation changes.

+10 QA since there were no code changes.  Merging.

**Pull request merged**
