### PR TITLE
DQC update version info to 2.0.2

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Updated _pkg_info to 2.0.2

### Pull request process

- [ ] Full description of changes provided above.
- [ ] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by joyreistad-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
QA +1 for version bump

**Comment by andrewperkins-wf** [comment]
No direct testing necessary since this is a version bump.

**Pull request merged**
