### PR TITLE
Update travisCI integration test cases.

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
### Changes:

- Out with the old test cases
- In with the new test cases

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by andrewperkins-wf** [comment]
+1 - lots of changes, ran through the files changed and they were all under the test cases directory.

**Comment by chrislococo-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Verified the ci build is still running cleanly.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-3212) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-3212) $

```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-3212) $ flake8 tests/
(dqc)  chrislococo [dqc] (XS-3212) $

```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-3212) $ nosetests tests/
...........................................................................................................
----------------------------------------------------------------------
Ran 107 tests in 0.091s

OK

```

#### Result: QA +10

**Comment by jasonleinbach-wf** [comment]
Reviewed and verified.  Merging.

**Pull request merged**
