### PR TITLE
Update release version to RC9

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Updated the release version to 2.0.0RC9

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
Version bump.  No testing necessary.  Merging.

**Pull request merged**
