### PR TITLE
Add attr checks for the cache.  Refs XS-3207

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
### Changes:

- Attr check on val.usgaapDeprecations

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [x] If this is a code change, reviewed by a second person. (+1)
- [x] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
Added in https://github.com/DataQualityCommittee/dqc_us_rules/pull/165 for a combined build.

**Comment by brianmyers-wf** [comment]
+1

**Comment by andrewperkins-wf** [comment]
+1 to the changes for this piece (the hasattr pieces)

**Comment by sagesmith-wf** [comment]
QA +10 Verified that error is no longer thrown

**Comment by jasonleinbach-wf** [comment]
https://github.com/DataQualityCommittee/dqc_us_rules/pull/165 functionality reviewed and tested under that PR.  Merging.

**Pull request merged**
