### PR TITLE
Release Candidate version update

### PR DESCRIPTION
**Pull request by andrewperkins-wf**
This is a version update for the 2.0.0.RC2 Release candidate.

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+10 - no testing needed.  This is purely a version update.

**Comment by andrewperkins-wf** [comment]
Reviews and testing notes completed - merging to finalize the 2.0.0.RC2 release

**Pull request merged**
