### PR TITLE
Refactor contains_insensitive

### PR DESCRIPTION
**Pull request by jasonleinbach-wf**
#### Changes:

- Changed function name
- updated tests

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by andrewperkins-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: TBA
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-2902) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-2902) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-2902) $ flake8 tests
(dqc)  chrislococo [dqc] (XS-2902) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-2902) $ nosetests tests/
......................................................................
----------------------------------------------------------------------
Ran 70 tests in 0.041s

OK

```

#### Result: TBA

**Comment by andrewperkins-wf** [comment]
QA'ed and reviewed.  Merging.

**Pull request merged**
