### PR TITLE
updated package meta to 1.0.8

### PR DESCRIPTION
**Pull request by andrewperkins-wf**
Package meta update for release

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: No manual testing needed on meta update.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (fix_ver_num) $ flake8 dqc_us_rules/
(dqc)  chrislococo [dqc] (fix_ver_num) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (fix_ver_num) $ flake8 tests/
(dqc)  chrislococo [dqc] (fix_ver_num) $
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (fix_ver_num) $ nosetests tests/
..................................................................
----------------------------------------------------------------------
Ran 66 tests in 0.063s

OK
```

#### Result: QA +10

**Comment by andrewperkins-wf** [comment]
Merging - has 2 +1s and a QA test.

**Pull request merged**
