### PR TITLE
RC3 Release PR

### PR DESCRIPTION
**Pull request by andrewperkins-wf**
made an RC3 since the RC2 was tagged wrong, and github does weird behavior with deleted tags.

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
+10 Release version change only, no additional QA steps required.

**Comment by andrewperkins-wf** [comment]
reviews and testing notes included.  Merging.

**Pull request merged**
