### PR TITLE
Fixed message

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes:

- Fixed message on dqc 18 from element.name to fact1.name

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by brianmyers-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
+1

**Comment by mindeerickson-wf** [comment]
QA +1

**Comment by jasonleinbach-wf** [comment]
Verified and reviewed.  Merging.

**Pull request merged**
