### PR TITLE
Update DQC's README.md with PR standards. 

### PR DESCRIPTION
**Pull request by chrislococo-wf**
#### Changes:

- Added `dist/` to the `.gitignore` file in order to prevent confusion with that directory when building the library locally and to prevent it accidentally being added.
- Updated the names of the requirements files to align better with convention.
- Updated the `README.md` with pull request standards and a standard PR template.

View of the updated readme: https://github.com/chrislococo-wf/dqc_us_rules/blob/XS-2855/README.md#requirements-for-a-pull-requestpr
Please review: @hefischer  @andrewperkins-wf
FYI: @susanyount-wf

Dependent on this PR: https://github.com/DataQualityCommittee/dqc_us_rules/pull/54

### CODE REVIEW

**Comment by chrislococo-wf** [comment]
Reviews completed on this PR
https://github.com/Workiva/dqc_us_rules/pull/5

**Comment by andrewperkins-wf** [comment]
+1 - merging documentation update

**Comment by davidtauriello** [comment]
Hi Andrew - The flake8 link on this .md file is a 404



https://github.com/DataQualityCommittee/dqc_us_rules/blob/master/README.md



David

David Tauriello
*Vice President, Member Services*

(202) 448-1985



*xbrl.us* <http://xbrl.us/> is the national consortium

for the business reporting standard.

*Earn the XBRL US GAAP Certificate*
An online CPE program

http://xbrl.us/certificate



*From:* andrewperkins-wf [mailto:notifications@github.com]
*Sent:* Tuesday, March 08, 2016 1:26 PM
*To:* DataQualityCommittee/dqc_us_rules
*Subject:* Re: [dqc_us_rules] Update DQC's README.md with PR standards.
(#55)



Merged #55 <https://github.com/DataQualityCommittee/dqc_us_rules/pull/55>.

—
Reply to this email directly or view it on GitHub
<https://github.com/DataQualityCommittee/dqc_us_rules/pull/55#event-582136250>
.

**Comment by chrislococo-wf** [comment]
@davidtauriello nice catch, I guess they moved their documentation. Correction is in this PR: https://github.com/DataQualityCommittee/dqc_us_rules/pull/57

**Pull request merged**
