### PR TITLE
XS-5103

### PR DESCRIPTION
**Pull request by allenbross-wf**
### Changes:

- Added ConsolidatedEntitiesAxis to exclusion rules to account for updates to the 2017 Taxonomy.
- Changed package version numbers

### Pull request process

- [x] Full description of changes provided above.
- [x] Reviewed by another person. (+1)
- [ ] If this is a code change, reviewed by a second person. (+1)
- [ ] QA'd to the specifications listed [here](https://github.com/DataQualityCommittee/dqc_us_rules#quality-assurance-qa-of-a-pull-request). Documentation only changes do not require the formal code quality assurance process. (+10)

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
+1

**Comment by derekgengenbacher-wf** [comment]
QA +10:
- Flake8 passes successfully
- Unit tests pass successfully
- Ran provided filing against rule in arelle GUI. As per the testing notes, the filing did not validate with any DQC errors

**Comment by allenbross-wf** [comment]
Code reviewed and verified. Merging.

**Pull request merged**
