### PR TITLE
Xs 3194

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes:

- Added the newest test cases to the dqc and updated some scripts
- Review files:
  * index.xml
  * run_integration.sh
  * run_integration.py

##### Note:

- look at the last commit

Please review: @hefischer  @andrewperkins-wf

### CODE REVIEW

**Comment by jasonleinbach-wf** [comment]
Can you remove the newlines again?  :-)

**Comment by brianmyers-wf** [comment]
+1

**Comment by jasonleinbach-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
refresh +1

**Comment by jasonleinbach-wf** [comment]
+10 - passing Travis build shows that we're running the new test cases.  No end-user functional change.

**Comment by andrewperkins-wf** [comment]
Tested and reviewed - merging

**Pull request merged**
