### PR TITLE
XS-3037 DQC rule 15 update

### PR DESCRIPTION
**Pull request by mindeerickson-wf**
##### Pull request for: [XS-3037](https://jira.webfilings.com/browse/XS-3037)
[XS-3037](https://jira.webfilings.com/browse/XS-3037) - DQC rule 15 update

-
#### Changes:
NOTE:  Changes made were based off instructions found here: https://github.com/DataQualityCommittee/dqc_us_rules/pull/99
1.  Performed all the additions to the Member Exclusion file
2.  Removed the following concepts from the concept file:
* 248,AllocatedShareBasedCompensationExpense
* 941,ExcessTaxBenefitFromShareBasedCompensationFinancingActivities
* 1366,InterestCreditedToPolicyOwnerAccounts
* 1937,PaymentsForProceedsFromFederalReserveBankStock
* 1782,NoncashOrPartNoncashAcquisitionNetNonmonetaryAssetsAcquiredLiabilitiesAssumed1

-
Please review: @jasonleinbach-wf @chrislococo-wf @andrewperkins-wf @brianmyers-wf @bradbenjamin-wf @derekgengenbacher-wf

### CODE REVIEW

**Comment by mindeerickson-wf** [comment]
Original PR:  https://github.com/DataQualityCommittee/dqc_us_rules/pull/106

**Comment by chrislococo-wf** [comment]
+1

**Comment by brianmyers-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
#### QA Steps: 

- Manual testing: Created and tested a new 0015 document against this branch and the current next_q1_16 branch. All the now exluded ones fire correctly, ignoring rule 15, while others still continue to fire.
- Flake8 on dqc_us_rules: 
```
(dqc)  chrislococo [dqc] (XS-3037) $ flake8 dqc_us_rules
(dqc)  chrislococo [dqc] (XS-3037) $
```
- Flake8 on tests: 
```
(dqc)  chrislococo [dqc] (XS-3037) $ flake8 tests/
tests/unit_tests/test_dqc_us_0013.py:81:80: E501 line too long (80 > 79 characters)
```
- Nosetest result: 
```
(dqc)  chrislococo [dqc] (XS-3037) $ nosetests
..................................................................................
----------------------------------------------------------------------
Ran 82 tests in 1.849s

OK
```

#### Result: QA +10, followup created for flake8 error.

**Comment by andrewperkins-wf** [comment]
Verified and tested - merging.

**Pull request merged**
